apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-quickstart-template
  title: Create a Quarkus Application form Quarkus Quickstarts
  description: Create a Quarkus App from Quarkus Quickstarts
  tags:
    - quarkus
    - java
    - maven
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - orgName
        - repoName
        - owner
        - system
        - port
      properties:
        orgName:
          title: Organization Name
          type: string
          default: org1
        repoName:
          title: Repository Name
          type: string
          default: repo1
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 8080
          description: Override the port exposed for the application

    - title: Provide information about the Java metadata
      required:
        - groupId
        - artifactId
        - version
        - java_package_name
        - quickstartName
      properties:
        groupId:
          title: Group ID
          type: string
          default: io.janus
          description: Maven Group ID eg (io.janus)
        artifactId:
          title: Artifact ID
          type: string
          default: quarkusapp
          description: Maven Artifact ID
        version:
          title: Version
          type: string
          default: 1.0.0-SNAPSHOT
          description: Maven Artifact Version
        java_package_name:
          title: Java Package Namespace
          type: string
          default: io.janus.quarkusapp
          description: Name for the Java Package (e.g. io.janus.quarkus.app)
        quickstartName:
          title: Quickstart Name
          type: string
          description: The name of the quickstart to clone
          default: 'hibernate-orm-panache'
          ui:field: QuarkusQuickstartPicker
        additionalProperties:
          title: Additional Properties
          type: string
          ui:widget: textarea
          ui:options:
            rows: 5

  steps:
    - id: template
      name: Generating the Source Code Component
      action: quarkus:quickstart:clone
      input:
        values:
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          version: ${{ parameters.version }}
          quickstartName: ${{ parameters.quickstartName }}
          additionalProperties: ${{ parameters.additionalProperties }}