apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-wizzard
  title: Create a Quarkus Application Wizzard
  description: Create a Quarkus App using a wizzard
  tags:
    - quarkus
    - java
    - maven
spec:
  owner: guests
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - orgName
        - repoName
        - owner
        - system
        - port
      properties:
        orgName:
          title: Organization Name
          type: string
          default: org1
        repoName:
          title: Repository Name
          type: string
          default: repo1
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 8080
          description: Override the port exposed for the application

    - title: Provide information about the Java metadata
      required:
        - groupId
        - artifactId
        - version
        - java_package_name
      properties:
        groupId:
          title: Group ID
          type: string
          default: io.janus
          description: Maven Group ID eg (io.janus)
        artifactId:
          title: Artifact ID
          type: string
          default: quarkusapp
          description: Maven Artifact ID
        version:
          title: Version
          type: string
          default: 1.0.0-SNAPSHOT
          description: Maven Artifact Version
        java_package_name:
          title: Java Package Namespace
          type: string
          default: io.janus.quarkusapp
          description: Name for the Java Package (e.g. io.janus.quarkus.app)
        javaVersion:
          title: Java Version
          type: string
          description: Java version
          default: '11'
          enum:
            - '11'
            - '17'
          enumNames:
            - Java 11
            - Java 17
        buildTool:
          title: Build Tool
          type: string
          description: The Build tool to use
          default: MAVEN
          enum:
            - MAVEN
            - GRADLE
            - GRADLE_KOTLIN_DSL
          enumNames:
            - Maven
            - Gradle
            - Gradle Kotlin DSL

    - title: Customize the Quarkus application features
      required:
        - healthEndpoint
        - metricsEndpoint
        - infoEndpoint
      properties:
        database:
          title: Enable database
          type: string
          default: none
          enum:
            - none
            - quarkus-jdbc-db2
            - quarkus-jdbc-mariadb
            - quarkus-jdbc-mssql
            - quarkus-jdbc-mysql
            - quarkus-jdbc-oracle
            - quarkus-jdbc-postgresql
          enumNames:
            - 'None'
            - 'DB2'
            - 'Maria DB'
            - 'MS SQL'
            - 'MySQL'
            - 'Oracle'
            - 'PostgreSQL'
        healthEndpoint:
          title: Enable health endpoints
          type: boolean
          default: true
          ui:widget: radio

        metricsEndpoint:
          title: Enable metrics endpoint
          type: boolean
          default: true
          ui:widget: radio

        infoEndpoint:
          title: Enable info endpoint
          type: boolean
          default: true
          ui:widget: radio

        extensions:
          title: Alternative Extensions
          type: array
          description: The list of alternative extensions
          ui:field: QuarkusExtensionList

        additionalProperties:
          title: Additional Properties
          type: string
          description: Additional Properties (to be appended to src/main/application.properties)
          ui:widget: textarea
          ui:options:
            rows: 5
  steps:
    - id: template
      name: Generating the Source Code Component
      action: quarkus:app:create
      input:
        values:
          groupId: ${{ parameters.groupId }}
          artifactId: ${{ parameters.artifactId }}
          version: ${{ parameters.version }}
          buildTool: ${{ parameters.buildTool }}
          javaVersion: ${{ parameters.javaVersion }}
          extensions: ${{ parameters.extensions }}
          database: ${{ parameters.database }}
          infoEndpoint: ${{ parameters.infoEndpoint }}
          healthEndpoint: ${{ parameters.healthEndpoint }}
          metricsEndpoint: ${{ parameters.metricsEndpoint }}
          additionalProperties: ${{ parameters.additionalProperties }}

#    - id: register
#      name: Registering the Catalog Info Component
#      action: catalog:register
#      input:
#        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
#        catalogInfoPath: /catalog-info.yaml
#
#  output:
#    links:
#      - title: Open the Source Code Repository
#        url: ${{ steps.publish.output.remoteUrl }}
#      - title: Open the Catalog Info Component
#        icon: catalog
#        entityRef: ${{ steps.register.output.entityRef }}