name: Publish packages to Node.js

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Build all plugins
        uses: ./.github/actions/build
        with:
          node_version: ${{ matrix.node-version }}

      - name: Verify dist files generated (*.d.ts)
        run: |
          ls -la plugins/*/dist

      - name: 'Login to npmjs npm repo .npmrc'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "always-auth = true" >> .npmrc

      # Publishes current version of packages that are not already present in the registry
      - name: publish
        run: |
          yarn workspace @qshift/plugin-quarkus run npm publish --registry https://registry.npmjs.org/ --access public --tag latest
          yarn workspace @qshift/plugin-quarkus-console run npm publish --registry https://registry.npmjs.org/ --access public --tag latest
          yarn workspace @qshift/plugin-quarkus-backend run npm publish --registry https://registry.npmjs.org/ --access public --tag latest