name: Update version and create Release PR

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write
  
jobs:
  version:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'

        - name: Install sponge tools
          run: sudo apt-get install -y moreutils

        - name: Build all plugins
          uses: ./.github/actions/build
          with:
            node_version: ${{ matrix.node-version }}

        - name: Verify dist files generated (*.d.ts)
          run: |
            ls -la plugins/*/dist

        - name: Setup Git
          run: |
              git config user.name "${{ github.actor }}"
              git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

        - name: Calculate next version
          id: calculate_next_version
          run: |
            yarn version --${{ github.event.inputs.version_type }} --no-git-tag-version --cwd plugins/quarkus/
            echo "version=$(cat plugins/quarkus/package.json  | jq .version -r)" >> $GITHUB_OUTPUT

        - name: Check if version already exists
          run: |
            VERSION_EXISTS=$(yarn info -s --json @qshift/plugin-quarkus | jq --arg lib_version ${{ steps.calculate_next_version.outputs.version }} '.data.versions | index($lib_version)')
            if [ $VERSION_EXISTS != "null" ]; then
              echo "::error ::Version $VERSION_EXISTS already exists."
              exit 1
            fi

        - name: Update package.json
          id: update_package_json
          run: |
            jq '.version = "${{ steps.calculate_next_version.outputs.version }}"' plugins/quarkus/package.json | sponge plugins/quarkus/package.json
            jq '.version = "${{ steps.calculate_next_version.outputs.version }}"' plugins/quarkus-backend/package.json | sponge plugins/quarkus-backend/package.json
            jq '.version = "${{ steps.calculate_next_version.outputs.version }}"' plugins/quarkus-console/package.json | sponge plugins/quarkus-console/package.json

        - name: List package.json files
          id: list_package_json_files
          run: |
            PLUGIN_FILES=$(find plugins/ -maxdepth 2 -name package.json -exec echo '  - `'{}'`' \;)
            echo "PLUGIN_FILES_MD<<EOF" >> $GITHUB_ENV
            echo "$PLUGIN_FILES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

        - name: Create pull request for release
          id: create_pr
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: release/${{ steps.calculate_next_version.outputs.version }}
            title: "Release: ${{ steps.calculate_next_version.outputs.version }}"
            body: |
              Pull request for release ${{ steps.calculate_next_version.outputs.version }}.

              This pull request contains the plugin `package.json` files updated with the new release version

              ${{ env.PLUGIN_FILES_MD }}
            base: main
            labels: |
              release